# Generated by Django 5.2.11 on 2026-03-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(max_length=250)),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('series', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=50)),
                ('published_year', models.IntegerField()),
                ('character', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
