# Generated by Django 5.2.11 on 2026-03-03 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookcrumbs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='character',
            new_name='characters',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='location',
            new_name='locations',
        ),
    ]
