# Generated by Django 5.2.11 on 2026-03-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcrumbs', '0002_rename_character_book_characters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.URLField(default='https://images.pexels.com/photos/1333742/pexels-photo-1333742.jpeg', max_length=250),
        ),
    ]
