# Generated by Django 5.2.11 on 2026-03-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcrumbs', '0003_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='characters',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='locations',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
